In [1]:
import torch
import torch.nn as nn
from config import device
import time

In [2]:
class stable_log_softmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x: torch.Tensor, dim: int=-1):
        max_values = torch.max(x, dim=dim, keepdim=True).values
        shifted_x = x - max_values
        log_probs = shifted_x - torch.logsumexp(shifted_x, dim=dim, keepdim=True)
        return log_probs

In [20]:
gen = torch.manual_seed(42)
x = torch.randn((1, 1, 50), requires_grad=True, generator=gen)

In [21]:
x = torch.nn.init.xavier_uniform_(x)

In [22]:
x

tensor([[[ 0.2032, -0.1452, -0.1461, -0.1461,  0.2203,  0.0816,  0.2357,
          -0.2022, -0.2430, -0.1916, -0.1648,  0.0992,  0.0877,  0.2035,
          -0.1265, -0.1670,  0.1300, -0.0990,  0.1487, -0.0581,  0.1401,
          -0.1903, -0.1236,  0.0747,  0.0518, -0.0625,  0.1460,  0.1665,
          -0.1776, -0.1308,  0.2243, -0.0827, -0.0868, -0.2370, -0.1403,
           0.0612, -0.0323, -0.1778,  0.0057, -0.1673, -0.2078, -0.1349,
          -0.2144, -0.1560,  0.2449,  0.0463,  0.0755, -0.2285, -0.1609,
          -0.0815]]], requires_grad=True)

In [23]:
m = stable_log_softmax()

In [24]:
seq_len = 10
total_log_prob = 1.0

In [30]:
torch.max(x, dim=-1).values.item()

0.2448531687259674

In [31]:
batch_size = 1
seq_len = 10
vocab_size = 50
gen = torch.manual_seed(42)
logits = torch.randn((batch_size, seq_len, vocab_size), generator=gen)
target_ids = torch.randint(0, vocab_size, (batch_size, seq_len), generator=gen)

In [33]:
logits[0, 0, :], target_ids[0, :]

(tensor([ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047,
         -0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624,
          1.6423, -0.1596, -0.4974,  0.4396, -0.7581,  1.0783,  0.8008,  1.6806,
          1.2791,  1.2964,  0.6105,  1.3347, -0.2316,  0.0418, -0.2516,  0.8599,
         -1.3847, -0.8712, -0.2234,  1.7174,  0.3189, -0.4245,  0.3057, -0.7746,
         -1.5576,  0.9956, -0.8798, -0.6011, -1.2742,  2.1228, -1.2347, -0.4879,
         -0.9138, -0.6581]),
 tensor([37, 39, 29,  7, 35, 38, 17, 14,  7, 24]))

In [34]:
out = torch.gather(logits, dim=-1, index=target_ids.unsqueeze(-1)).squeeze(-1)

In [35]:
out.shape

torch.Size([1, 10])

In [36]:
out

tensor([[-0.4245, -0.4816,  1.0119, -0.4175, -1.0811,  0.9733, -0.0553, -1.7735,
         -0.0388,  0.4151]])

In [38]:
logits[0, 1, target_ids[0, 1]]

tensor(-0.4816)

In [39]:
torch.sum(out, dim=-1)

tensor([-1.8721])

In [13]:
from maths.sequence_score import sequence_logprob, compute_nll
from maths.softmax import stable_log_softmax

In [4]:
m_sftmax = stable_log_softmax()

In [9]:
gen1 = torch.manual_seed(42)
gen2 = torch.manual_seed(43)
logits_a = torch.randn((10, 2, 50), generator=gen1)
target_ids_a = torch.randint(0, 50, (10, 2), generator=gen1)
logits_b = torch.randn((10, 10, 50), generator=gen2)
target_ids_b = torch.randint(0, 50, (10, 10), generator=gen2)

In [10]:
seq_probs_a = sequence_logprob(logits_a, target_ids_a)
seq_probs_b = sequence_logprob(logits_b, target_ids_b)

In [11]:
seq_probs_a

tensor([ -9.5571,  -6.9069, -12.4230,  -8.7082, -11.6055, -10.6919,  -9.3203,
        -10.5201,  -8.8899,  -6.3690])

In [12]:
seq_probs_b

tensor([-46.3163, -44.3665, -44.4756, -40.5072, -49.0028, -42.1155, -37.8311,
        -42.5875, -46.1512, -46.3185])

In [14]:
seq_nll_a = compute_nll(logits_a, target_ids_a)
seq_nll_b = compute_nll(logits_b, target_ids_b)

In [15]:
seq_nll_a, seq_nll_b

(tensor(4.7496), tensor(4.3967))

In [2]:
from maths.softmax import stable_log_softmax, stable_softmax

In [3]:
stb_sft = stable_softmax()
stb_log_sft = stable_log_softmax()

In [18]:
def compute_entropy(logits: torch.Tensor):
    probs = stb_sft(logits, dim=-1)
    log_probs = stb_log_sft(logits, dim=-1)
    out = - torch.sum(probs * log_probs, dim=-1)
    return out

In [19]:
gen = torch.manual_seed(42)
logits_a = torch.ones((1, 50))
logits_b = torch.ones((1, 50))
logits_b[0, 4], logits_b[0, 23] = 100, 100

In [20]:
logits_a, logits_b

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[  1.,   1.,   1.,   1., 100.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
            1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,
            1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
            1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
            1.,   1.]]))

In [21]:
out_a = compute_entropy(logits_a)
out_b = compute_entropy(logits_b)

In [22]:
out_a, out_b

(tensor([3.9120]), tensor([0.6931]))

In [23]:
torch.exp(out_a), torch.exp(out_b)

(tensor([50.0000]), tensor([2.]))

In [27]:
temp_values = [0.01, 0.1, 0.2, 0.5, 0.6, 0.8, 1.0, 5.0, 10.0, 25.0, 60.0, 100.0]

In [28]:
for t in temp_values:
    print(compute_entropy(logits_b/t))

tensor([0.6931])
tensor([0.6931])
tensor([0.6931])
tensor([0.6931])
tensor([0.6931])
tensor([0.6931])
tensor([0.6931])
tensor([0.6931])
tensor([0.7063])
tensor([2.3129])
tensor([3.7734])
tensor([3.8777])


In [29]:
for t in temp_values:
    print(compute_entropy(logits_a/t))

tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])
tensor([3.9120])


In [30]:
import math
print(math.log(2))

0.6931471805599453


In [95]:
def sample(logits: torch.Tensor, temperature: float=1.0, top_k: int=5, top_p: float= 0.9):
    B, C = logits.shape
    probs = stb_sft(logits/temperature, dim=-1)
    sort_probs, sort_indices = torch.sort(probs, dim=-1, descending=True)
    sort_probs = sort_probs[:, :top_k]
    sort_indices = sort_indices[:, :top_k]
    valid_indices = torch.where(~(torch.cumsum(sort_probs, dim=-1) > top_p), sort_indices, -1)
    return valid_indices

In [96]:
gen = torch.manual_seed(42) 
logits = torch.randn((2, 50), generator=gen)

In [97]:
logits

tensor([[ 1.9269e+00,  1.4873e+00,  9.0072e-01, -2.1055e+00,  6.7842e-01,
         -1.2345e+00, -4.3067e-02, -1.6047e+00, -7.5214e-01,  1.6487e+00,
         -3.9248e-01, -1.4036e+00, -7.2788e-01, -5.5943e-01, -7.6884e-01,
          7.6245e-01,  1.6423e+00, -1.5960e-01, -4.9740e-01,  4.3959e-01,
         -7.5813e-01,  1.0783e+00,  8.0080e-01,  1.6806e+00,  1.2791e+00,
          1.2964e+00,  6.1047e-01,  1.3347e+00, -2.3162e-01,  4.1759e-02,
         -2.5158e-01,  8.5986e-01, -1.3847e+00, -8.7124e-01, -2.2337e-01,
          1.7174e+00,  3.1888e-01, -4.2452e-01,  3.0572e-01, -7.7459e-01,
         -1.5576e+00,  9.9564e-01, -8.7979e-01, -6.0114e-01, -1.2742e+00,
          2.1228e+00, -1.2347e+00, -4.8791e-01, -9.1382e-01, -6.5814e-01],
        [ 7.8024e-02,  5.2581e-01, -4.8799e-01,  1.1914e+00, -8.1401e-01,
         -7.3599e-01, -1.4032e+00,  3.6004e-02, -6.3477e-02,  6.7561e-01,
         -9.7807e-02,  1.8446e+00, -1.1845e+00,  1.3835e+00,  1.4451e+00,
          8.5641e-01,  2.2181e+00,  5

In [98]:
out = sample(logits, top_p=0.2)

In [99]:
out

tensor([[45,  0, -1, -1, -1],
        [16, 11, -1, -1, -1]])

In [6]:
from maths.softmax import stable_log_softmax, stable_softmax
import math

In [7]:
stb_sft = stable_softmax()
stb_log_sft = stable_log_softmax()

In [8]:
def compute_entropy(logits: torch.Tensor):
    probs = stb_sft(logits, dim=-1)
    log_probs = stb_log_sft(logits, dim=-1)
    out = -torch.sum(probs * log_probs, dim=-1)
    return out
    

In [9]:
gen = torch.manual_seed(42)
logits_a = torch.ones((1, 50))
logits_b = torch.ones((1, 50))
logits_b[0, 4] = 100
logits_b[0, 25] = 100
logits_b[0, 43] = 89
logits_c = torch.randn((1, 50), generator=gen)

In [10]:
logits_b

tensor([[  1.,   1.,   1.,   1., 100.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
           1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
           1., 100.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
           1.,   1.,   1.,   1.,   1.,   1.,   1.,  89.,   1.,   1.,   1.,   1.,
           1.,   1.]])

In [11]:
out_a = compute_entropy(logits_a)
out_b = compute_entropy(logits_b)
out_c = compute_entropy(logits_c)

In [12]:
out_a, out_b, out_c

(tensor([3.9120]), tensor([0.6932]), tensor([3.4912]))

In [13]:
torch.exp(out_a), torch.exp(out_b), torch.exp(out_c)

(tensor([50.0000]), tensor([2.0002]), tensor([32.8249]))

In [14]:
temp = [0.01, 0.1, 0.2, 0.3, 0.6, 0.9, 1.0, 5.0, 10.0, 15.0, 20.0, 50.0]

In [15]:
for t in temp:
    ent = compute_entropy(logits_b/t)
    print(t, ent, torch.exp(ent))

0.01 tensor([0.6931]) tensor([2.])
0.1 tensor([0.6931]) tensor([2.])
0.2 tensor([0.6931]) tensor([2.])
0.3 tensor([0.6931]) tensor([2.])
0.6 tensor([0.6931]) tensor([2.0000])
0.9 tensor([0.6932]) tensor([2.0001])
1.0 tensor([0.6932]) tensor([2.0002])
5.0 tensor([0.8626]) tensor([2.3692])
10.0 tensor([1.0149]) tensor([2.7591])
15.0 tensor([1.2381]) tensor([3.4492])
20.0 tensor([1.7435]) tensor([5.7173])
50.0 tensor([3.6309]) tensor([37.7482])


In [16]:
probs = stb_sft(logits_c, dim=-1)
torch.topk(probs, dim=-1, k = 5)

torch.return_types.topk(
values=tensor([[0.0759, 0.0699, 0.0593, 0.0575, 0.0571]]),
indices=tensor([[ 0, 45, 23,  9, 16]]))

In [54]:
def sample(logits: torch.Tensor, temperature: float=1.0, top_k: int=10, top_p: float=0.9):
    # top-k
    logits, logits_indices = torch.topk(logits, k=top_k, dim=-1)
    
    probs = stb_sft(logits/temperature, dim=-1)
    
    # top-p
    cumsum = torch.cumsum(probs, dim=-1)
    mask = cumsum <= top_p
    mask[:, 0] = True
    mask[:, 1:] |= (cumsum[:, :-1] <= top_p)
    probs = torch.where(mask, probs, torch.zeros_like(probs))
    probs = probs / torch.sum(probs, dim=-1, keepdim=True)
    indices = torch.multinomial(probs, num_samples=1)
    return torch.gather(logits_indices, dim=-1, index=indices)

In [57]:
def sample(logits: torch.Tensor, temperature: float=1.0, top_k: int=10, top_p: float=0.9):
    probs = stb_sft(logits/temperature, dim=-1)
    # top-k
    probs, prob_indices = torch.topk(probs, k=top_k, dim=-1)
    
    # top-p
    cumsum = torch.cumsum(probs, dim=-1)
    mask = cumsum <= top_p
    mask[:, 0] = True
    mask[:, 1:] |= (cumsum[:, :-1] <= top_p)
    probs = torch.where(mask, probs, torch.zeros_like(probs))
    probs = probs / torch.sum(probs, dim=-1, keepdim=True)
    indices = torch.multinomial(probs, num_samples=1)
    print(prob_indices.shape, indices.shape)
    return torch.gather(prob_indices, dim=-1, index=indices)
     

In [55]:
gen = torch.manual_seed(42)
logits = torch.randn((2, 50), generator=gen)

In [58]:
sample(logits, top_p=0.2, top_k=5)

torch.Size([2, 5]) torch.Size([2, 1])


tensor([[ 0],
        [14]])

In [61]:
def compute_nll(logits: torch.Tensor, target_ids: torch.Tensor):
    B, T, C = logits.shape
    B_t, T_t = target_ids.shape
    assert B==B_t and T == T_t
    log_probs = stb_log_sft(logits, dim=-1)
    log_probs = torch.gather(log_probs, dim=-1, index=target_ids.unsqueeze(-1)).squeeze(-1)
    out = - torch.sum(log_probs)/(T*B)
    return out

In [63]:
gen = torch.manual_seed(42)
logits = torch.randn((2, 10, 50), generator=gen)
target_ids = torch.randint(0, 50, (2, 10), generator=gen)

In [70]:
out = compute_nll(logits, target_ids)
out_e = compute_entropy(logits)
out_e = torch.sum(out_e)/out_e.numel()
out, out_e

(tensor(4.4533), tensor(3.4519))

In [71]:
torch.exp(out), torch.exp(out_e)

(tensor(85.9116), tensor(31.5609))

In [72]:
gen = torch.manual_seed(42)
cheating = torch.randn((2, 1, 50), generator=gen)
cheating[0, 0, 10] = 25
cheating[1, 0, 21] = 100
target_ids = torch.tensor([[10], [21]])
clueless = torch.ones((2, 1, 50))
print(target_ids.shape, cheating.shape, clueless.shape)

torch.Size([2, 1]) torch.Size([2, 1, 50]) torch.Size([2, 1, 50])


In [73]:
out_cheating = compute_nll(cheating, target_ids)
out_clueless = compute_nll(clueless, target_ids)
out_cheating, out_clueless

(tensor(-0.), tensor(3.9120))

In [74]:
torch.exp(out_cheating), torch.exp(out_clueless)

(tensor(1.), tensor(50.0000))

In [2]:
from maths.softmax import stable_softmax
from config import device
import torch.nn as nn

In [66]:
class SelfAttention(nn.Module):
    def __init__(self, dim: int, seq_len: int, num_head:int, head_dim: int, is_causal: bool=True):
        super().__init__()
        self.dim = dim
        self.seq_len = seq_len
        self.num_head = num_head
        self.head_dim = head_dim
        self.is_causal = is_causal
        self.q_w = nn.Linear(self.dim, self.num_head * self.head_dim)
        self.k_w = nn.Linear(self.dim, self.num_head * self.head_dim)
        self.v_w = nn.Linear(self.dim, self.num_head * self.head_dim)

        self.w_o = nn.Linear(self.num_head * self.head_dim, self.dim)
        self.stb_sft = stable_softmax()
        self.register_buffer('tril', torch.tril(torch.ones((seq_len, seq_len)).bool()).unsqueeze(0).unsqueeze(1))
    
    def forward(self, x, scale=True, mask = None):
        B, T, C = x.shape
        q = self.q_w(x)
        k = self.k_w(x)
        v = self.v_w(x)

        q = q.contiguous().view(B, T, self.num_head, self.head_dim).transpose(1, 2)
        k = k.contiguous().view(B, T, self.num_head, self.head_dim).transpose(1, 2)
        v = v.contiguous().view(B, T, self.num_head, self.head_dim).transpose(1, 2)

        attn = (q @ k.transpose(-2, -1)) 
        if scale:
            attn *= (self.head_dim ** -0.5)
        if self.is_causal:
            attn = attn.masked_fill(~self.tril[:, :, :T, :T], value=float('-inf'))
        
        if mask is not None:
            if mask.dim()==2:
                mask = mask.unsqueeze(1).unsqueeze(1)
            attn = attn.masked_fill(~mask, value=float('-inf'))
        
        attn_scores = self.stb_sft(attn, dim=-1)

        out = attn_scores @ v
        out = out.transpose(1, 2).reshape(B, T, self.num_head*self.head_dim)
        out = self.w_o(out)

        return out, attn_scores

In [30]:
B = 10
T = 256
C = 512
num_head = 4

In [31]:
attns_module = SelfAttention(dim=C, seq_len=T, num_head=num_head, head_dim=C//num_head).to(device)

In [32]:
gen = torch.Generator(device=device)
gen.manual_seed(42)

x = torch.randn((B, T, C), generator=gen, device=device)

In [33]:
x.shape

torch.Size([10, 256, 512])

In [34]:
out = attns_module(x)

In [35]:
out.shape

torch.Size([10, 256, 512])

In [36]:
out[0, 0, :]

tensor([ 2.4783e-01,  3.6095e-02, -2.5217e-02,  3.2824e-02,  6.1090e-02,
         9.3080e-02, -4.7263e-01,  6.9629e-02, -1.1324e-01,  2.0311e-02,
         4.7459e-01, -2.7355e-01, -1.1605e-01,  3.3105e-01, -2.0175e-01,
        -3.1972e-01, -1.6648e-01, -4.8679e-01, -4.1119e-02,  1.3437e-01,
        -3.1591e-01, -4.6594e-01, -1.0267e-01,  3.6037e-01, -2.0170e-01,
         4.2192e-01,  7.4926e-03, -6.2227e-01, -2.0499e-01, -1.0794e-01,
        -4.6283e-01, -2.4208e-01, -1.0251e-01,  7.6484e-02,  1.4384e-01,
         4.1377e-01,  3.4608e-01, -4.2251e-01,  5.0063e-02,  1.4665e-01,
         2.0903e-01,  2.0728e-01,  5.6482e-01,  3.7572e-01, -3.2820e-01,
        -2.6438e-01,  4.6083e-01,  2.1955e-01, -3.0335e-01, -1.5517e-01,
         2.5395e-01,  1.2230e-01, -7.5012e-02, -3.0587e-01, -2.7703e-01,
        -2.6285e-01, -6.8638e-01,  7.8786e-02,  5.1866e-01,  2.4602e-01,
         6.1291e-01,  6.4392e-02, -2.7970e-01, -3.5646e-01, -2.6253e-01,
         4.5659e-01, -1.4787e-01, -5.6352e-01,  2.2

In [37]:
class ProjLayer(nn.Module):
    def __init__(self, dim: int, vocab_size: int):
        super().__init__()
        self.dim = dim
        self.vocab_size = vocab_size
        self.proj = nn.Linear(self.dim, self.vocab_size)
        self.stb_sft = stable_softmax()
    
    def forward(self, x):
        B, T, C = x.shape
        out = self.proj(x)
        out = self.stb_sft(out, dim=-1)
        return out


In [38]:
out.shape, C

(torch.Size([10, 256, 512]), 512)

In [39]:
proj_layer = ProjLayer(dim=C, vocab_size=1000).to(device)

In [40]:
final_out = proj_layer(out)

In [41]:
final_out.shape

torch.Size([10, 256, 1000])

In [67]:
class EmbeddingLayer(nn.Module):
    def __init__(self, vocab_size: int, dim: int):
        super().__init__()
        self.dim = dim
        self.vocab_size = vocab_size
        self.embddings = nn.Embedding(self.vocab_size, self.dim)
    
    def forward(self, x):
        return self.embddings(x)


In [68]:
B = 10
T = 256
C = 512
VOCAB_SIZE = 1000
num_head = 4
head_dim = C//num_head

In [69]:
embedding_layer = EmbeddingLayer(VOCAB_SIZE, C).to(device)

In [90]:
gen = torch.Generator(device)
gen.manual_seed(42)
x = torch.randint(0, VOCAB_SIZE, (B, T), device=device, generator=gen)

In [91]:
x.shape

torch.Size([10, 256])

In [92]:
x = embedding_layer(x)

In [93]:
x.shape

torch.Size([10, 256, 512])

In [94]:
attns_module = SelfAttention(dim=C, seq_len=T, num_head=num_head, head_dim=head_dim).to(device)

In [95]:
out, attn_scores = attns_module(x)
out_1, attn_scores_1 = attns_module(x, False)

In [96]:
out.shape, out_1.shape, attn_scores.shape, attn_scores_1.shape

(torch.Size([10, 256, 512]),
 torch.Size([10, 256, 512]),
 torch.Size([10, 4, 256, 256]),
 torch.Size([10, 4, 256, 256]))

In [97]:
attn_scores[0, 0, 10, :], attn_scores_1[0, 0, 10, :]

(tensor([0.1874, 0.0777, 0.0590, 0.0857, 0.0689, 0.0429, 0.1742, 0.0507, 0.0532,
         0.0686, 0.1318, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

In [85]:
sum_probs = torch.sum(attn_scores, dim=-1)
sum_probs[0, 0, :]

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [98]:
def compute_entropy_cutome(probs: torch.Tensor):
    B, H, T, C = probs.shape
    log_probs = torch.log(probs)
    out = -(torch.sum(probs * log_probs)/(B*T*H))
    return out

In [81]:
entropy_score = compute_entropy_cutome(attn_scores)
entropy_score_1 = compute_entropy_cutome(attn_scores_1)

In [82]:
entropy_score, entropy_score_1

(tensor(nan, device='mps:0', grad_fn=<NegBackward0>),
 tensor(nan, device='mps:0', grad_fn=<NegBackward0>))

In [57]:
proj_layer = ProjLayer(dim=C, vocab_size=VOCAB_SIZE).to(device)

In [58]:
final_out = proj_layer(out)
final_out1 = proj_layer(out_1)

In [59]:
final_out.shape, final_out1.shape

(torch.Size([10, 256, 1000]), torch.Size([10, 256, 1000]))

In [60]:
from maths.softmax import stable_softmax, stable_log_softmax
stb_sft = stable_softmax()
stb_log_sft = stable_log_softmax()

In [63]:
def compute_entropy_cutome(logits: torch.Tensor):
    B, T, C = logits.shape
    probs = stb_sft(logits, dim=-1)
    log_probs = stb_log_sft(logits, dim=-1)
    out = -(torch.sum(probs * log_probs)/(B*T))
    return out

In [64]:
compute_entropy_cutome(final_out)

tensor(6.9078, device='mps:0', grad_fn=<NegBackward0>)

In [65]:
compute_entropy_cutome(final_out1)

tensor(6.9078, device='mps:0', grad_fn=<NegBackward0>)

In [57]:
class TestSelfAttention(nn.Module):
    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim
        self.wq = nn.Linear(dim, dim)
        self.wk = nn.Linear(dim, dim)
    
    def forward(self, x, scale=True):
        B, T, C = x.shape
        q = torch.randn((B, T, C), device=device)
        k = torch.randn((B, T, C), device=device)

        attn_logits = q @ k.transpose(-2, -1)
        if scale:
            attn_logits *= (C ** -0.5)

        return attn_logits
    

In [58]:
gen = torch.Generator(device=device)
gen.manual_seed(42)
x = torch.randn((1, 10, 64), device=device, generator=gen)

In [59]:
torch.var(x, dim=-1)

tensor([[0.9574, 0.9336, 1.0007, 0.8275, 1.2791, 1.0770, 0.8818, 1.0969, 0.7752,
         1.0255]], device='mps:0')

In [60]:
attn_module = TestSelfAttention(dim=64).to(device)

In [61]:
attn_logits_scaled = attn_module(x)
attn_logits_normal = attn_module(x, False)

In [62]:
from maths.softmax import stable_softmax, stable_log_softmax
from maths.entropy import compute_entropy

In [63]:
stb_sft = stable_softmax()
stb_log_sft = stable_log_softmax()

In [64]:
probs_scaled = stb_sft(attn_logits_scaled)
probs_normal = stb_sft(attn_logits_normal)

In [65]:
max_probs_scaled = torch.max(probs_scaled, dim=-1)
max_probs_normal = torch.max(probs_normal, dim=-1)

In [66]:
max_probs_scaled.values, max_probs_normal.values

(tensor([[0.2985, 0.2035, 0.3186, 0.3146, 0.3412, 0.2326, 0.2452, 0.2122, 0.4324,
          0.2953]], device='mps:0'),
 tensor([[0.7714, 0.9980, 0.9998, 0.9314, 0.6220, 0.9258, 0.8858, 0.9125, 0.9783,
          0.9531]], device='mps:0'))

In [67]:
entropy_scaled = compute_entropy(attn_logits_scaled)
entropy_normal = compute_entropy(attn_logits_normal)

In [68]:
entropy_scaled, entropy_normal

(tensor(20.0606, device='mps:0'), tensor(3.0130, device='mps:0'))

In [70]:
var_scaled = torch.var(attn_logits_scaled, unbiased=False)
var_normal = torch.var(attn_logits_normal, unbiased=False)

In [71]:
var_scaled, var_normal

(tensor(0.7883, device='mps:0'), tensor(51.7235, device='mps:0'))

In [53]:
torch.exp(entropy_scaled), torch.exp(entropy_normal) #--> this should give us, on how many options the model is going to guess on.

(tensor(1.4047e+08, device='mps:0'), tensor(5.6832, device='mps:0'))

In [56]:
dims = [64, 128, 256, 512, 1026, 2048]
entropy_list = []
var_list = []

In [ ]:
gen = torch.Generator(device=device)
gen.manual_seed(42)
x = torch.randn((1, 10, 64), device=device, generator=gen)
for dk in dims:
    attn_logits = attn_module(x, False)
    probs = stb_sft(attn_logits)
    max_probs = torch.max(probs, dim=-1)
    
